import { randomUUID } from "crypto";
import { readdir, readFile } from "fs/promises";
import path from "path";
import { NextResponse } from "next/server";
import { getAvailableMatches, getMatchById } from "@/lib/cloudbet/cloudbet-service";
import type { CloudbetMarket, CloudbetMatch, CloudbetOddsSelection } from "@/lib/cloudbet/cloudbet-types";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const SPORT_ANALYST_SKILL_DIR = ".agents/skills/sport-analyst";
const OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses";
const OPENAI_MODEL = process.env.OPENAI_MODEL ?? "gpt-4.1-mini";
const ANALYSIS_SPORTS = ["basketball"] as const;
const ENABLED_SELECTION_STATUS = "SELECTION_ENABLED";
const ANALYSIS_MATCH_LIMIT_PER_SPORT = Number(process.env.CRON_ANALYSIS_MATCH_LIMIT_PER_SPORT ?? 100);
const PAYIN = 1;
const MIN_MODEL_PROBABILITY = 65;
const MIN_TOTAL_QUOTA = 1.5;
const MAX_TOTAL_QUOTA = 2.2;
const NO_MARKETS_MESSAGE = "No basketball matches with available marketplaces found."
const NO_VALID_TICKET_MESSAGE = "No valid ticket found. Requirements not met: probability above 65% and quota between 1.5 and 2.2.";
const PENDING_TICKET_MESSAGE = "Ticket generated by AI and awaiting manual review.";

type AnalysisSport = (typeof ANALYSIS_SPORTS)[number];

type MatchSelection = {
  candidateId: string;
  matchId: number;
  marketUrl: string;
  outcome: string;
  price: number;
  status: string;
  minStake: number;
  maxStake: number;
  sportKey?: string;
  matchName?: string;
  competitionName?: string;
  marketKey?: string;
  params?: string;
  side?: string;
  probability?: number;
  cutoffTime?: string;
};

type ProposedBetBody = {
  currency: "USDT";
  eventId: string;
  marketUrl: string;
  outcome: string;
  price: number;
  referenceId: string;
  stake: number;
};

type StoredMatchSelection = MatchSelection & {
  analysis: SelectionAnalysis;
  proposedBetBody?: ProposedBetBody;
};

type SportTicketStatus = "PENDING_REVIEW" | "FAILED";

type SportTicketInsert = {
  status: SportTicketStatus;
  currency: "USDT";
  matches: StoredMatchSelection[];
  total_quota: number | null;
  payin: number;
  possible_payout: number | null;
  is_played: boolean;
  played_successfully: boolean | null;
  message: string;
  reference_id: string;
};

type SportTicketInsertResult = {
  id: string | number;
};

type SelectionAnalysis = {
  candidateId: string;
  assessedProbability: number;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  summary: string;
  risks: string[];
};

type AiTicketAnalysis = {
  decision: "PROPOSE_TICKET" | "NO_BET";
  message: string;
  selectedCandidateIds: string[];
  analyzedSelections: SelectionAnalysis[];
};

type OpenAIResponsesPayload = {
  model: string;
  instructions: string;
  input: string;
  store: boolean;
  text: {
    format: {
      type: "json_schema";
      name: string;
      strict: boolean;
      schema: Record<string, unknown>;
    };
  };
};

type OpenAIResponseContent = {
  type?: string;
  text?: string;
};

type OpenAIResponseOutput = {
  type?: string;
  content?: OpenAIResponseContent[];
};

type OpenAIResponsesResponse = {
  output_text?: string;
  output?: OpenAIResponseOutput[];
};

type ErrorResponse = {
  message: string;
};

function jsonError(message: string, status: number) {
  return NextResponse.json<ErrorResponse>({ message }, { status });
}

function getMissingEnvVars() {
  return ["OPENAI_API_KEY", "CRON_SECRET"].filter((key) => !process.env[key]);
}

function isAllowedAnalysisSport(sportKey?: string): sportKey is AnalysisSport {
  return sportKey === "basketball";
}

function inferSportKey(selection: Pick<MatchSelection, "sportKey" | "marketUrl">) {
  if (isAllowedAnalysisSport(selection.sportKey)) {
    return selection.sportKey;
  }

  const marketSport = selection.marketUrl.split(".")[0];
  return isAllowedAnalysisSport(marketSport) ? marketSport : selection.sportKey;
}

function createCandidateId(selection: Pick<MatchSelection, "matchId" | "marketUrl" | "outcome">) {
  return `${selection.matchId}:${selection.marketUrl}:${selection.outcome}`;
}

function isMatchSelection(value: unknown): value is MatchSelection {
  if (!value || typeof value !== "object") {
    return false;
  }

  const selection = value as Partial<MatchSelection>;

  return (
    typeof selection.matchId === "number" &&
    Number.isInteger(selection.matchId) &&
    typeof selection.marketUrl === "string" &&
    typeof selection.outcome === "string" &&
    typeof selection.price === "number" &&
    Number.isFinite(selection.price) &&
    typeof selection.status === "string" &&
    typeof selection.minStake === "number" &&
    Number.isFinite(selection.minStake) &&
    typeof selection.maxStake === "number" &&
    Number.isFinite(selection.maxStake)
  );
}

function normalizeSelection(selection: MatchSelection): MatchSelection {
  return {
    ...selection,
    candidateId: selection.candidateId || createCandidateId(selection),
    sportKey: inferSportKey(selection),
  };
}

function getMatchesFromBody(body: unknown): unknown {
  if (Array.isArray(body)) {
    return body;
  }

  if (body && typeof body === "object" && "matches" in body) {
    return (body as { matches?: unknown }).matches;
  }

  return undefined;
}

function getSelections(market: CloudbetMarket): CloudbetOddsSelection[] {
  if (market.selections?.length) {
    return market.selections;
  }

  return Object.values(market.submarkets ?? {}).flatMap((submarket) => submarket.selections ?? []);
}

function selectionToMatchSelection(
  match: CloudbetMatch,
  marketKey: string,
  selection: CloudbetOddsSelection,
): MatchSelection | null {
  if (!selection.marketUrl || selection.minStake === undefined || selection.maxStake === undefined) {
    return null;
  }

  const matchSelection = {
    candidateId: "",
    matchId: match.id,
    marketUrl: selection.marketUrl,
    outcome: selection.outcome,
    price: selection.price,
    status: selection.status ?? "UNKNOWN",
    minStake: selection.minStake,
    maxStake: selection.maxStake,
    sportKey: match.sport?.key,
    matchName: match.name,
    competitionName: match.competition?.name,
    marketKey,
    params: selection.params,
    side: selection.side,
    probability: selection.probability,
    cutoffTime: match.cutoffTime,
  } satisfies MatchSelection;

  return normalizeSelection(matchSelection);
}

function isEnabledAnalysisSelection(selection: MatchSelection) {
  return (
    selection.status === ENABLED_SELECTION_STATUS &&
    isAllowedAnalysisSport(selection.sportKey) &&
    selection.price > 0 &&
    selection.minStake > 0 &&
    selection.maxStake > 0
  );
}

function extractMatchSelections(match: CloudbetMatch): MatchSelection[] {
  return Object.entries(match.markets ?? {}).flatMap(([marketKey, market]) =>
    getSelections(market)
      .map((selection) => selectionToMatchSelection(match, marketKey, selection))
      .filter((selection): selection is MatchSelection => selection !== null)
      .filter(isEnabledAnalysisSelection),
  );
}

async function loadCloudbetAnalysisSelections() {
  const matchesById = new Map<number, CloudbetMatch>();

  for (const sport of ANALYSIS_SPORTS) {
    const matches = await getAvailableMatches({ sport, limit: ANALYSIS_MATCH_LIMIT_PER_SPORT });

    matches.forEach((match) => {
      if (isAllowedAnalysisSport(match.sport?.key ?? sport)) {
        matchesById.set(match.id, match);
      }
    });
  }

  const detailedMatches = await Promise.allSettled(
    Array.from(matchesById.values()).map((match) =>
      getMatchById(String(match.id), { sport: match.sport?.key }).catch((error) => {
        console.warn("[cron:analyze-matches:cloudbet:match-detail:error]", { matchId: match.id, error });
        return match;
      }),
    ),
  );

  return detailedMatches.flatMap((settledMatch) =>
    settledMatch.status === "fulfilled" ? extractMatchSelections(settledMatch.value) : [],
  );
}

function filterEnabledSelections(selections: MatchSelection[]) {
  return selections.map(normalizeSelection).filter(isEnabledAnalysisSelection);
}

function mapToProposedBetBody(selection: MatchSelection): ProposedBetBody {
  return {
    currency: "USDT",
    eventId: selection.matchId.toString(),
    marketUrl: selection.marketUrl,
    outcome: selection.outcome,
    price: selection.price,
    referenceId: randomUUID(),
    stake: PAYIN,
  };
}

function calculateTotalQuota(selections: MatchSelection[]) {
  if (selections.length === 0) {
    return null;
  }

  return selections.reduce((totalQuota, selection) => totalQuota * selection.price, 1);
}

function isQuotaInRange(totalQuota: number | null) {
  return totalQuota !== null && totalQuota >= MIN_TOTAL_QUOTA && totalQuota <= MAX_TOTAL_QUOTA;
}

function getAnalysisByCandidateId(analysis: AiTicketAnalysis) {
  return new Map(analysis.analyzedSelections.map((selectionAnalysis) => [selectionAnalysis.candidateId, selectionAnalysis]));
}

function getHighProbabilitySelections(selections: MatchSelection[], analysis: AiTicketAnalysis) {
  const analysisByCandidateId = getAnalysisByCandidateId(analysis);

  return selections.filter((selection) => {
    const selectionAnalysis = analysisByCandidateId.get(selection.candidateId);
    return selectionAnalysis !== undefined && selectionAnalysis.assessedProbability > MIN_MODEL_PROBABILITY;
  });
}

function buildSelectedTicketSelections(selections: MatchSelection[], analysis: AiTicketAnalysis) {
  const highProbabilitySelections = getHighProbabilitySelections(selections, analysis);
  const highProbabilityIds = new Set(highProbabilitySelections.map((selection) => selection.candidateId));
  const selectedIds = analysis.selectedCandidateIds.filter((candidateId) => highProbabilityIds.has(candidateId));
  const selectedIdSet = new Set(selectedIds);

  return highProbabilitySelections.filter((selection) => selectedIdSet.has(selection.candidateId));
}

function groupSelectionsByMatch(selections: MatchSelection[]) {
  const groups = new Map<number, MatchSelection[]>();

  selections.forEach((selection) => {
    const group = groups.get(selection.matchId) ?? [];
    group.push(selection);
    groups.set(selection.matchId, group);
  });

  return Array.from(groups.values()).sort((left, right) => {
    const leftCutoff = left[0]?.cutoffTime ? new Date(left[0].cutoffTime).getTime() : Number.MAX_SAFE_INTEGER;
    const rightCutoff = right[0]?.cutoffTime ? new Date(right[0].cutoffTime).getTime() : Number.MAX_SAFE_INTEGER;

    return leftCutoff - rightCutoff;
  });
}

function getProjectedQuota(currentSelections: MatchSelection[], nextSelection: MatchSelection) {
  const currentQuota = calculateTotalQuota(currentSelections) ?? 1;
  return currentQuota * nextSelection.price;
}

function getIncrementalSelection(currentSelections: MatchSelection[], candidateSelections: MatchSelection[], analysis: AiTicketAnalysis) {
  const selectedCandidates = buildSelectedTicketSelections(candidateSelections, analysis);

  return selectedCandidates.find((selection) => getProjectedQuota(currentSelections, selection) <= MAX_TOTAL_QUOTA);
}

function mergeAnalyses(analyses: AiTicketAnalysis[], selectedSelections: MatchSelection[]): AiTicketAnalysis {
  const analyzedSelections = new Map<string, SelectionAnalysis>();

  analyses.forEach((analysis) => {
    analysis.analyzedSelections.forEach((selectionAnalysis) => {
      analyzedSelections.set(selectionAnalysis.candidateId, selectionAnalysis);
    });
  });

  return {
    decision: selectedSelections.length > 0 ? "PROPOSE_TICKET" : "NO_BET",
    message: selectedSelections.length > 0 ? "Incremental basketball ticket analysis completed." : NO_VALID_TICKET_MESSAGE,
    selectedCandidateIds: selectedSelections.map((selection) => selection.candidateId),
    analyzedSelections: Array.from(analyzedSelections.values()),
  };
}

async function buildIncrementalTicket(openaiApiKey: string, skillPrompt: string, enabledSelections: MatchSelection[]) {
  const selectedSelections: MatchSelection[] = [];
  const analyses: AiTicketAnalysis[] = [];

  for (const matchSelections of groupSelectionsByMatch(enabledSelections)) {
    const currentQuota = calculateTotalQuota(selectedSelections);

    if (isQuotaInRange(currentQuota)) {
      break;
    }

    const analysis = await createAnalysis(openaiApiKey, skillPrompt, matchSelections, selectedSelections);
    analyses.push(analysis);

    if (analysis.decision !== "PROPOSE_TICKET") {
      continue;
    }

    const nextSelection = getIncrementalSelection(selectedSelections, matchSelections, analysis);

    if (!nextSelection) {
      continue;
    }

    selectedSelections.push(nextSelection);

    if (isQuotaInRange(calculateTotalQuota(selectedSelections))) {
      break;
    }
  }

  return {
    analysis: mergeAnalyses(analyses, selectedSelections),
    selectedSelections,
  };
}

function buildStoredMatches(
  selections: MatchSelection[],
  analysis: AiTicketAnalysis,
  proposedBetBodies: ProposedBetBody[] = [],
): StoredMatchSelection[] {
  const analysisByCandidateId = getAnalysisByCandidateId(analysis);
  const proposedBetByCandidateId = new Map(
    proposedBetBodies.map((proposedBetBody) => [
      createCandidateId({
        matchId: Number(proposedBetBody.eventId),
        marketUrl: proposedBetBody.marketUrl,
        outcome: proposedBetBody.outcome,
      }),
      proposedBetBody,
    ]),
  );

  return selections.flatMap((selection) => {
    const selectionAnalysis = analysisByCandidateId.get(selection.candidateId);

    if (!selectionAnalysis) {
      return [];
    }

    return {
      ...selection,
      analysis: selectionAnalysis,
      proposedBetBody: proposedBetByCandidateId.get(selection.candidateId),
    };
  });
}

function buildSportTicketInsert(params: {
  status: SportTicketStatus;
  matches: StoredMatchSelection[];
  totalQuota: number | null;
  payin: number;
  message: string;
  playedSuccessfully: boolean | null;
}): SportTicketInsert {
  return {
    status: params.status,
    currency: "USDT",
    matches: params.matches,
    total_quota: params.totalQuota,
    payin: params.payin,
    possible_payout: params.totalQuota === null ? null : params.totalQuota * params.payin,
    is_played: false,
    played_successfully: params.playedSuccessfully,
    message: params.message,
    reference_id: randomUUID(),
  };
}

async function insertSportTicket(ticket: SportTicketInsert) {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("sport_tickets")
    .insert(ticket)
    .select("id")
    .single<SportTicketInsertResult>();

  if (error) {
    console.error("[cron:analyze-matches:sport_tickets:insert:error]", error);
    throw new Error("Unable to persist generated sport ticket.");
  }

  if (!data) {
    console.error("[cron:analyze-matches:sport_tickets:insert:empty]");
    throw new Error("Unable to persist generated sport ticket.");
  }

  return data.id;
}

async function loadSportAnalystSkills() {
  const skillDirectory = path.join(process.cwd(), SPORT_ANALYST_SKILL_DIR);
  const entries = await readdir(skillDirectory, { withFileTypes: true });
  const markdownFiles = entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".md"))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const contents = await Promise.all(
    markdownFiles.map(async (fileName) => {
      const filePath = path.join(skillDirectory, fileName);
      const content = await readFile(filePath, "utf8");

      return `# ${fileName}\n\n${content.trim()}`;
    }),
  );

  return contents.join("\n\n---\n\n");
}

function buildAnalysisInput(selections: MatchSelection[], currentTicketSelections: MatchSelection[] = []) {
  return [
    "Analyze only this one basketball match group and decide whether to add at most one selection from it to the current ticket.",
    "Return JSON only. Do not include markdown or prose outside the JSON object.",
    `Only select an outcome where your assessed probability is greater than ${MIN_MODEL_PROBABILITY}%.`,
    `The final combined decimal quota must be between ${MIN_TOTAL_QUOTA} and ${MAX_TOTAL_QUOTA}.`,
    "If adding a selection from this match would be weak, unsafe, or push quota above the maximum, return decision NO_BET.",
    "Do not place any bet or call any betting API. This route only creates a stored proposal.",
    "Consider form, H2H, injuries, suspensions, expected/confirmed lineups, motivation, schedule congestion, relevant news, market integrity concerns, and any reasons to avoid a bet.",
    "Current ticket selections already accepted by previous analysis steps:",
    JSON.stringify(currentTicketSelections, null, 2),
    "Candidate selections for this one basketball match:",
    JSON.stringify(selections, null, 2),
  ].join("\n\n");
}

function getAnalysisJsonSchema() {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      decision: { type: "string", enum: ["PROPOSE_TICKET", "NO_BET"] },
      message: { type: "string" },
      selectedCandidateIds: {
        type: "array",
        items: { type: "string" },
      },
      analyzedSelections: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            candidateId: { type: "string" },
            assessedProbability: { type: "number", minimum: 0, maximum: 100 },
            confidence: { type: "string", enum: ["HIGH", "MEDIUM", "LOW"] },
            summary: { type: "string" },
            risks: {
              type: "array",
              items: { type: "string" },
            },
          },
          required: ["candidateId", "assessedProbability", "confidence", "summary", "risks"],
        },
      },
    },
    required: ["decision", "message", "selectedCandidateIds", "analyzedSelections"],
  };
}

function extractOutputText(response: OpenAIResponsesResponse) {
  if (typeof response.output_text === "string" && response.output_text.trim()) {
    return response.output_text.trim();
  }

  const outputText = response.output
    ?.flatMap((output) => output.content ?? [])
    .filter((content) => content.type === "output_text" && typeof content.text === "string")
    .map((content) => content.text)
    .join("\n")
    .trim();

  if (!outputText) {
    throw new Error("No analysis text returned by OpenAI.");
  }

  return outputText;
}

function isSelectionAnalysis(value: unknown): value is SelectionAnalysis {
  if (!value || typeof value !== "object") {
    return false;
  }

  const analysis = value as Partial<SelectionAnalysis>;

  return (
    typeof analysis.candidateId === "string" &&
    typeof analysis.assessedProbability === "number" &&
    Number.isFinite(analysis.assessedProbability) &&
    (analysis.confidence === "HIGH" || analysis.confidence === "MEDIUM" || analysis.confidence === "LOW") &&
    typeof analysis.summary === "string" &&
    Array.isArray(analysis.risks) &&
    analysis.risks.every((risk) => typeof risk === "string")
  );
}

function parseAiTicketAnalysis(text: string): AiTicketAnalysis {
  const parsed = JSON.parse(text) as unknown;

  if (!parsed || typeof parsed !== "object") {
    throw new Error("OpenAI analysis did not return a JSON object.");
  }

  const analysis = parsed as Partial<AiTicketAnalysis>;

  if (
    (analysis.decision !== "PROPOSE_TICKET" && analysis.decision !== "NO_BET") ||
    typeof analysis.message !== "string" ||
    !Array.isArray(analysis.selectedCandidateIds) ||
    !analysis.selectedCandidateIds.every((candidateId) => typeof candidateId === "string") ||
    !Array.isArray(analysis.analyzedSelections) ||
    !analysis.analyzedSelections.every(isSelectionAnalysis)
  ) {
    throw new Error("OpenAI analysis JSON does not match the expected ticket schema.");
  }

  return {
    decision: analysis.decision,
    message: analysis.message,
    selectedCandidateIds: analysis.selectedCandidateIds,
    analyzedSelections: analysis.analyzedSelections,
  };
}

async function createAnalysis(
  openaiApiKey: string,
  skillPrompt: string,
  selections: MatchSelection[],
  currentTicketSelections: MatchSelection[] = [],
) {
  const payload: OpenAIResponsesPayload = {
    model: OPENAI_MODEL,
    instructions: skillPrompt,
    input: buildAnalysisInput(selections, currentTicketSelections),
    store: false,
    text: {
      format: {
        type: "json_schema",
        name: "sport_ticket_analysis",
        strict: true,
        schema: getAnalysisJsonSchema(),
      },
    },
  };

  const response = await fetch(OPENAI_RESPONSES_URL, {
    method: "POST",
    headers: {
      authorization: `Bearer ${openaiApiKey}`,
      "content-type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    let message = `OpenAI Responses API request failed with status ${response.status}.`;

    try {
      const errorBody = (await response.json()) as { error?: { message?: string } };
      message = errorBody.error?.message ?? message;
    } catch {
      // Keep the generic upstream error message.
    }

    throw new Error(message);
  }

  return parseAiTicketAnalysis(extractOutputText((await response.json()) as OpenAIResponsesResponse));
}

async function insertFailedTicket(message: string, matches: StoredMatchSelection[] = []) {
  const ticket = buildSportTicketInsert({
    status: "FAILED",
    matches,
    totalQuota: null,
    payin: 0,
    message,
    playedSuccessfully: false,
  });
  const ticketId = await insertSportTicket(ticket);

  return { ticket, ticketId };
}

export async function POST(request: Request) {
  const missingEnvVars = getMissingEnvVars();

  if (missingEnvVars.length > 0) {
    return jsonError("Cron analysis endpoint is not configured.", 500);
  }

  const cronSecret = process.env.CRON_SECRET as string;
  const openaiApiKey = process.env.OPENAI_API_KEY as string;

  if (request.headers.get("x-cron-secret") !== cronSecret) {
    return jsonError("Unauthorized cron request.", 401);
  }

  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return jsonError("Invalid JSON request body.", 400);
  }

  try {
    const matches = getMatchesFromBody(body);
    let candidateSelections: MatchSelection[];

    if (matches === undefined) {
      candidateSelections = await loadCloudbetAnalysisSelections();
    } else if (Array.isArray(matches) && matches.every(isMatchSelection)) {
      candidateSelections = matches.map(normalizeSelection);
    } else {
      return jsonError("Request body must include a matches array of MatchSelection objects or omit matches to fetch basketball selections.", 400);
    }

    if (candidateSelections.length === 0) {
      const { ticketId } = await insertFailedTicket(NO_MARKETS_MESSAGE);

      return NextResponse.json({
        success: true,
        ticketId,
        status: "FAILED",
        message: NO_MARKETS_MESSAGE,
      });
    }

    const enabledSelections = filterEnabledSelections(candidateSelections);

    if (enabledSelections.length === 0) {
      const { ticketId } = await insertFailedTicket(NO_VALID_TICKET_MESSAGE);

      return NextResponse.json({
        success: true,
        ticketId,
        status: "FAILED",
        message: NO_VALID_TICKET_MESSAGE,
      });
    }

    const skillPrompt = await loadSportAnalystSkills();
    const { analysis, selectedSelections } = await buildIncrementalTicket(openaiApiKey, skillPrompt, enabledSelections);
    const totalQuota = calculateTotalQuota(selectedSelections);

    if (selectedSelections.length === 0 || !isQuotaInRange(totalQuota)) {
      const analyzedMatches = buildStoredMatches(getHighProbabilitySelections(enabledSelections, analysis), analysis);
      const { ticketId } = await insertFailedTicket(NO_VALID_TICKET_MESSAGE, analyzedMatches);

      return NextResponse.json({
        success: true,
        ticketId,
        status: "FAILED",
        message: NO_VALID_TICKET_MESSAGE,
      });
    }

    const proposedBetBodies = selectedSelections.map(mapToProposedBetBody);
    const pendingMatches = buildStoredMatches(selectedSelections, analysis, proposedBetBodies);
    const pendingTicketInsert = buildSportTicketInsert({
      status: "PENDING_REVIEW",
      matches: pendingMatches,
      totalQuota,
      payin: PAYIN,
      message: PENDING_TICKET_MESSAGE,
      playedSuccessfully: null,
    });
    const ticketId = await insertSportTicket(pendingTicketInsert);

    return NextResponse.json({
      success: true,
      ticketId,
      status: pendingTicketInsert.status,
      message: pendingTicketInsert.message,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to analyze matches.";

    console.error("[cron:analyze-matches:error]", error);
    return jsonError(message, 500);
  }
}
